In [1]:
%run config.py

/Users/noahkarsky/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cognite/client/_cognite_client.py:80: UserWarning: You are using version 2.31.0 of the SDK, however version 2.32.0 is available. Upgrade or set the environment variable 'COGNITE_DISABLE_PYPI_VERSION_CHECK' to suppress this warning.
  self._config = ClientConfig(

In [2]:
from cognite.client import CogniteClient
from cognite.client.data_classes import Asset
from cognite.client.data_classes import DataSet
import os
import mimetypes
import pandas as pd

We already created a dataset id, so I do not include the code to do so. You can learn more about their purpose [in our CDF documentation](https://pr-573.docs.preview.cogniteapp.com/cdf/data_governance/concepts/datasets/)

In [3]:
UTAH_FORGE_DATASET_ID  = 8185991842002062
UTAH_FORGE_FILE_DATASET_ID = 2443662041002176

typically, a root asset will need to be created manually as it is more of a grouping concept one can use to organize assets.

In [4]:
#make a root asset for all the wells
root = c.assets.retrieve(external_id='Utah Forge Wells')
if root is None:
    root_asset = Asset(name="Utah Forge Wells", external_id='Utah Forge Wells',    data_set_id=UTAH_FORGE_DATASET_ID)
    root_asset = c.assets.create(root_asset)
    print("Created root asset")
else:
    print("Root asset already exists")

Root asset already exists

Now that we have the root asset we can add our wells under it. As with many things with Python, there are many ways to go about this. Since we only have three assets to create I am going to just do it manually using dictionaries. I also had no structured way of getting this data, so I simply copied it from the end of well report and various supporting documentation.

In [13]:
#creating our first well asset under the root asset. It is the 68-32
well_data = {
    "Area": "Milford, Utah",
    "Field": "FORGE,Utah",
    "Operator": "University of Utah",
    "Well Name": '68-32',
    "Well Type": "Shallow Monitoring Well",
    "Lat": 38.501591,
    "Long": -112.886654,
    "CRS": "WGS84 UTM Zone 11",
    "ref_elevation": 5.7,
    "ref_elevation_unit": "ft",
    "TD":1000,
    "TD_unit":"ft",
}

#create a well asset
well_asset = Asset(name="68-32", data_set_id=UTAH_FORGE_DATASET_ID, parent_id=root_asset.id, metadata=well_data,external_id="68-32")
well_asset = c.assets.create(well_asset)

In [ ]:
folder_path = r"1153_drilling_data_well_loc/2019-well-68-32"
# make a list of all files in all folders in folder_path
file_list = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        file_list.append(os.path.join(root, file))

# we could call file upload once for all files, but I wanted to use mimetypes to get the mime type
[
    c.files.upload(
        x,
        data_set_id=UTAH_FORGE_FILE_DATASET_ID,
        asset_ids=[2698410095292759],
        mime_type=mimetypes.guess_type(x)[0],
    )
    for x in file_list
]

In [55]:
#now we create an asset for the 78-32 well
well_data = {
    "Area": "Milford, Utah",
    "Field": "FORGE,Utah",
    "Operator": "University of Utah",
    "Well Name": '78-32',
    "Well Type": "Shallow Monitoring Well",
    "Lat": 38.500182,
    "Long": -112.883229,
    "CRS": "WGS84 UTM Zone 12",
    "ref_elevation": 5.7,
    "ref_elevation_unit": "ft",
    "TD":3280,
    "TD_unit":"ft",
}

#create a well asset
well_asset = Asset(name="78-32", data_set_id=UTAH_FORGE_DATASET_ID, parent_id=root_asset.id, metadata=well_data,external_id="78-32")
well_asset = c.assets.create(well_asset)

In [ ]:

#upload files for this well
folder_path = r"1153_drilling_data_well_loc/2019-well-78-32"
# make a list of all files in all folders in folder_path
file_list = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        file_list.append(os.path.join(root, file))

# we could call file upload once for all files, but I wanted to use mimetypes to get the mime type
[
    c.files.upload(
        x,
        data_set_id=UTAH_FORGE_FILE_DATASET_ID,
        asset_ids=[620746848006],
        mime_type=mimetypes.guess_type(x)[0],
    )
    for x in file_list
]

In [66]:
#we will now upload data for our 3rd well in this dataset 58-32
well_data = {
    "Area": "Milford, Utah",
    "Field": "FORGE,Utah",
    "Well Name": '58-32',
    "Well Type": "deep test wel",
    "Lat": 38.500439,
    "Long": -112.885531,
    "CRS": "WGS84 UTM Zone 11",
    "ref_elevation": 21.5,
    "ref_elevation_unit": "ft",
    "TD":7515,
    "TD_unit":"ft",
}

#create a well asset
well_asset = Asset(name="58-32", data_set_id=UTAH_FORGE_DATASET_ID, parent_id=root_asset.id, metadata=well_data,external_id="MU-ESW1")
well_asset = c.assets.create(well_asset)

In [ ]:
folder_path = r"1006/well58_32_files"
# make a list of all files in all folders in folder_path
file_list = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        file_list.append(os.path.join(root, file))

# we could call file upload once for all files, but I wanted to use mimetypes to get the mime type
[
    c.files.upload(
        x,
        data_set_id=UTAH_FORGE_FILE_DATASET_ID,
        asset_ids=[214760900481346],
        mime_type=mimetypes.guess_type(x)[0],
    )
    for x in file_list
]

We have created three assets and uploaded all the associated files. In the next notebook I will work on some of the log data contained in .las files.

In [5]:
forge_assets = c.assets.list(limit=None,data_set_ids=[UTAH_FORGE_DATASET_ID]).to_pandas()
forge_assets

,externalId,name,parentId,parentExternalId,dataSetId,metadata,id,createdTime,lastUpdatedTime,rootId
0,78-32,78-32,926520837699232,Utah Forge Wells,8185991842002062,"{'Area': 'Milford, Utah', 'CRS': 'WGS84 UTM Zo...",620746848006,1636136745282,1636136745282,926520837699232
1,MU-ESW1,58-32,926520837699232,Utah Forge Wells,8185991842002062,"{'Area': 'Milford, Utah', 'CRS': 'WGS84 UTM Zo...",214760900481346,1636144565502,1636144565502,926520837699232
2,Utah Forge Wells,Utah Forge Wells,<NA>,NaN,8185991842002062,{},926520837699232,1636126947739,1636126947739,926520837699232
3,68-32,68-32,926520837699232,Utah Forge Wells,8185991842002062,"{'Area': 'Milford, Utah', 'CRS': 'WGS84 UTM Zo...",2698410095292759,1636126950640,1636126950640,926520837699232

In [6]:
c.files.list(limit=None, data_set_ids=[UTAH_FORGE_FILE_DATASET_ID]).to_pandas()

,name,mimeType,assetIds,dataSetId,id,uploaded,uploadedTime,createdTime,lastUpdatedTime
0,DailyReportSummaryRpt11-20170806.pdf,application/pdf,[214760900481346],2443662041002176,71304028766620,True,1636144631413,1636144631038,1636144631038
1,DailyReportGraphicalRpt61-20170925.pdf,application/pdf,[214760900481346],2443662041002176,117422032282861,True,1636144641164,1636144640843,1636144640843
2,IMG_1413.JPG,image/jpeg,[2698410095292759],2443662041002176,144498198995306,True,1636131290963,1636131290339,1636131290339
3,DirectionalSurveyRpt_171027103004.pdf,application/pdf,[214760900481346],2443662041002176,148594131224829,True,1636144604563,1636144604157,1636144604157
4,DailyReportSummaryRpt19-20170814.pdf,application/pdf,[214760900481346],2443662041002176,152441586237726,True,1636144660759,1636144660459,1636144660459
...,...,...,...,...,...,...,...,...,...
218,Schlumberger_FMI_run2_feature_picks.xlsx,application/vnd.openxmlformats-officedocument....,[214760900481346],2443662041002176,8816662659369183,True,1636144670098,1636144669776,1636144669776
219,DailyReportDetailRpt_190315090724.pdf,application/pdf,[620746848006],2443662041002176,8852473259888475,True,1636137018106,1636137017783,1636137017783
220,PTS_University_of_Utah_MU-ESW1_FMI_Borehole_St...,image/jpeg,[214760900481346],2443662041002176,8883545635113635,True,1636144664991,1636144664692,1636144664692
221,DailyReportGraphicalRpt40-20170904.pdf,application/pdf,[214760900481346],2443662041002176,8957060763987481,True,1636144650129,1636144649673,1636144649673
222,DailyReportSummaryRpt10-20170805.pdf,application/pdf,[214760900481346],2443662041002176,8996715870582785,True,1636144637800,1636144637480,1636144637480